# fly.toml app configuration file generated for code-purple-leaf-5110 on 2024-07-25T10:16:14-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'code-purple-leaf-5110'
primary_region = 'sjc'

[build]


[http_service]
  auto_stop_machines = true
  auto_start_machines = true
  force_https = true
  internal_port = 80
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
